FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-runtime
# FROM  pytorch/pytorch:2.3.0-cuda12.1-cudnn8-runtime
# RUN nvidia-smi  # uncomment to enforce GPU availability during the run

ARG UID=1000
ARG GID=1000

# create a new user with same UID & PID but no password
RUN groupadd --gid ${GID} ibladmin && \
    useradd --create-home ibladmin --uid=${UID} --gid=${GID} --groups root && \
    passwd --delete ibladmin
# add user to the sudo group and set sudo group to no passoword
RUN apt update && \
    apt install -y sudo && \
    adduser ibladmin sudo && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# install system packages and clean-up cache
RUN apt-get update && apt-get install -y \
    vim \
    gcc \
    git \
    libfftw3-dev \
    libfftw3-doc \
    rsync \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*

# setup default user when enter the container
RUN chown -fR ibladmin:ibladmin /opt/conda
USER ${UID}:${GID}
RUN mkdir -p /home/ibladmin/Documents/PYTHON
WORKDIR /home/ibladmin/Documents/PYTHON

# install iblsorter
RUN conda install -c conda-forge cupy cuda-version=12.4

RUN git clone -b aws https://github.com/int-brain-lab/ibl-sorter.git
RUN git clone -b develop https://github.com/int-brain-lab/ibllib.git
RUN git clone https://github.com/int-brain-lab/iblscripts.git
RUN git clone -b iblsorter https://github.com/int-brain-lab/dartsort.git
RUN git clone -b v0.2.2 https://github.com/evarol/dredge.git

# RUN pip install cupy-cuda12x
RUN pip install -r ibl-sorter/requirements.txt
RUN pip install -r dartsort/requirements-full.txt
RUN pip install -r dredge/requirements.txt
RUN pip install -e ./ibl-sorter
RUN pip install -e ./dartsort
RUN pip install -e ./dredge
RUN pip install h5py
RUN pip install hdbscan
RUN pip install ipython
RUN pip uninstall -y ibllib
RUN pip install -e ./ibllib
RUN pip install prefect
