FROM internationalbrainlab/iblsorter_base:latest

ARG ibllib_branch=master

ENV TQDM_DISABLE=1
ENV DART_SIGNALS_DISABLE=0
ENV MKL_SERVICE_FORCE_INTEL=1
ENV MKL_THREADING_LAYER=GNU

WORKDIR /home/ibladmin/Documents/PYTHON

RUN git -C ./ibl-sorter pull
RUN git -C ./ibllib fetch origin ${ibllib_branch}
RUN git -C ./ibllib checkout -B ${ibllib_branch} origin/${ibllib_branch}
RUN pip install -e ./ibllib

RUN git -C ./ibl-sorter pull


WORKDIR /home/ibladmin/Documents/PYTHON/prefect
ADD ./iblserver_prefect.py /home/ibladmin/Documents/PYTHON/prefect/iblserver_prefect.py
