FROM prefecthq/prefect:3-python3.12

ARG UID=1000
ARG GID=1000

# create a new user with same UID & PID but no password
RUN groupadd --gid ${GID} ibladmin && \
    useradd --create-home ibladmin --uid=${UID} --gid=${GID} --groups root && \
    passwd --delete ibladmin
# add user to the sudo group and set sudo group to no passoword
RUN apt update && \
    apt install -y sudo && \
    adduser ibladmin sudo && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# install system packages and clean-up cache
RUN apt-get update && apt-get install -y \
    vim \
    gcc \
    git \
    ffmpeg \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*

# setup default user when enter the container
USER ${UID}:${GID}

# install ibllib
RUN mkdir -p /home/ibladmin/Documents/PYTHON/prefect
WORKDIR /home/ibladmin/Documents/PYTHON

RUN git clone https://github.com/int-brain-lab/ibllib.git
RUN git clone https://github.com/int-brain-lab/iblscripts.git

RUN pip install -e ./ibllib
RUN pip install prefect[dask]
