#docker build -t internationalbrainlab/dlc:base -f Dockerfile.base
FROM nvidia/cuda:11.8.0-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive 
ENV LANG=C.UTF-8
ENV TF_FORCE_GPU_ALLOW_GROWTH=true

ARG PYTHON=python3.11
ARG UID=1000
ARG GID=1000

# create a new user with same UID & PID but no password
RUN groupadd --gid ${GID} ibladmin && \
    useradd --create-home ibladmin --uid=${UID} --gid=${GID} --groups root && \
    passwd --delete ibladmin
# add user to the sudo group and set sudo group to no passoword
RUN apt update && \
    apt install -y sudo && \
    adduser ibladmin sudo && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Update the package list and install necessary dependencies
RUN apt-get update && apt-get install -y \
    software-properties-common \
    libsm6 \
    libxext6 \
    libgtk-3-dev \
    build-essential \
    wget \
    vim \
    git \
    ffmpeg

# The apt-add-repository command is installed by software-properties common above
RUN apt-add-repository -y ppa:deadsnakes/ppa && apt-get update && apt-get install -y ${PYTHON}

# Clean up
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Python by creating symlinks and getting the latest pip
RUN ln -sf /usr/bin/${PYTHON} /usr/local/bin/python3
RUN ln -sf /usr/bin/${PYTHON} /usr/local/bin/python
RUN wget https://bootstrap.pypa.io/get-pip.py && python get-pip.py
RUN python -m pip install -U setuptools
RUN python --version && pip --version

# From now on we operate as user ibladmin
USER ${UID}:${GID}
WORKDIR /home/ibladmin/Documents/PYTHON

RUN git clone https://github.com/int-brain-lab/ibllib.git
RUN pip install -e ./ibllib

# Install DLC
RUN pip install --upgrade deeplabcut
RUN pip install tensorflow==2.12
RUN pip install numpy==1.24.0 decorator==4.4.2
RUN pip install prefect
RUN pip install ipython tensorpack tf_slim

# Create folders
RUN mkdir -p /home/ibladmin/Documents/PYTHON/prefect
WORKDIR /home/ibladmin/Documents/PYTHON
