FROM internationalbrainlab/ibllib_base:latest

WORKDIR /root/Documents/PYTHON

RUN git -C ./ibllib pull
RUN git -C ./ibllib checkout prefect

WORKDIR /root/Documents/PYTHON/prefect

ADD ./iblserver_prefect.py /root/Documents/PYTHON/prefect/iblserver_prefect.py
ADD ./prefect-service-entrypoint.sh /root/Documents/PYTHON/prefect/prefect-service-entrypoint.sh

RUN prefect work-pool create --type docker iblserver-docker-pool
RUN prefect worker start --pool iblserver-docker-pool
# NB: this needs to be run here: the relative path of this script needs to be the same as the relative path in the worker container
RUN python iblserver_prefect.py
