# This Dockerfile uses a multi-stage build to select a base image based on the CUDA_MAJOR_VERSION argument.
#
# Build for CUDA 11 (default):
# docker buildx build . -f Dockerfile_iblsorter_base_torch -t iblsorter_base:cuda11
# Build for CUDA 12:
# docker buildx build . -f Dockerfile_iblsorter_base_torch --build-arg CUDA_MAJOR_VERSION=12 -t iblsorter_base:cuda12
# Build for CUDA 13:
# docker buildx build . -f Dockerfile_iblsorter_base_torch --build-arg CUDA_MAJOR_VERSION=13 -t iblsorter_base:cuda13

ARG CUDA_MAJOR_VERSION=12

# --- Base image definitions ---
# Define a stage for each possible base image and set the corresponding full CUDA version.
FROM pytorch/pytorch:2.7.1-cuda11.8-cudnn9-runtime as base-cuda11
ARG CUDA_VERSION=11.8

FROM pytorch/pytorch:2.9.0-cuda12.8-cudnn9-runtime as base-cuda12
ARG CUDA_VERSION=12.8

FROM pytorch/pytorch:2.9.0-cuda13.0-cudnn9-runtime as base-cuda13
ARG CUDA_VERSION=13.0

# --- Common build steps ---
# This stage will be based on the selected CUDA version
FROM base-cuda${CUDA_MAJOR_VERSION} as builder

ARG UID=1000
ARG GID=1000

# create a new user with same UID & PID but no password
RUN groupadd --gid ${GID} ibladmin && \
    useradd --create-home ibladmin --uid=${UID} --gid=${GID} --groups root && \
    passwd --delete ibladmin
# add user to the sudo group and set sudo group to no passoword
RUN apt update && \
    apt install -y sudo && \
    adduser ibladmin sudo && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# install system packages and clean-up cache
RUN apt-get update && apt-get install -y \
    vim \
    gcc \
    git \
    libfftw3-dev \
    libfftw3-doc \
    rsync \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*

# setup default user when enter the container
RUN conda install -c conda-forge cupy cuda-version=${CUDA_VERSION}

USER ${UID}:${GID}
RUN mkdir -p /home/ibladmin/Documents/PYTHON
WORKDIR /home/ibladmin/Documents/PYTHON

RUN git clone -b main https://github.com/int-brain-lab/ibl-sorter.git
RUN git clone -b develop https://github.com/int-brain-lab/ibllib.git
RUN git clone https://github.com/int-brain-lab/iblscripts.git
RUN git clone -b iblsorter https://github.com/int-brain-lab/dartsort.git
RUN git clone -b v0.2.2 https://github.com/evarol/dredge.git

RUN pip install -r ibl-sorter/requirements.txt --no-cache-dir
RUN pip install -r dartsort/requirements-full.txt --no-cache-dir
RUN pip install -r dredge/requirements.txt --no-cache-dir
RUN pip install -e ./ibl-sorter --no-cache-dir
RUN pip install -e ./dartsort --no-cache-dir
RUN pip install -e ./dredge --no-cache-dir
RUN pip install h5py --no-cache-dir
RUN pip install hdbscan --no-cache-dir
RUN pip install ipython --no-cache-dir
RUN pip uninstall -y ibllib
RUN pip install -e ./ibllib --no-cache-dir
RUN pip install prefect --no-cache-dir
