# docker buildx build . --pull --platform linux/amd64 --tag internationalbrainlab/iblsorter:1.12  -f Dockerfile_iblsorter --no-cache --build-arg ibllib_branch=prefect
FROM internationalbrainlab/iblsorter_base:cuda11

ARG ibllib_branch=master
ARG iblsorter_version=1.12.0
ENV TQDM_DISABLE=1
ENV DART_SIGNALS_DISABLE=0
ENV MKL_SERVICE_FORCE_INTEL=1
ENV MKL_THREADING_LAYER=GNU

WORKDIR /home/ibladmin/Documents/PYTHON

# Pull a specific tag for ibl-sorter
RUN git -C ./ibl-sorter fetch --tags
RUN git -C ./ibl-sorter checkout ${iblsorter_version}

RUN git -C ./ibllib fetch origin ${ibllib_branch}
RUN git -C ./ibllib checkout -B ${ibllib_branch} origin/${ibllib_branch}
RUN pip install -e ./ibllib
RUN pip install -e ./ibl-sorter


WORKDIR /home/ibladmin/Documents/PYTHON/prefect
ADD ./iblserver_prefect.py /home/ibladmin/Documents/PYTHON/prefect/iblserver_prefect.py
