FROM internationalbrainlab/dlc_base:latest

ENV TQDM_DISABLE=1

ARG ibllib_branch=master

WORKDIR /home/ibladmin/Documents/PYTHON

RUN git -C ./ibllib fetch origin ${ibllib_branch}
RUN git -C ./ibllib checkout -B ${ibllib_branch} origin/${ibllib_branch}
RUN pip install -e ./ibllib

RUN git clone --depth 1 --single-branch --branch master https://github.com/int-brain-lab/iblvideo.git
ENV PYTHONPATH=/home/ibladmin/Documents/PYTHON/iblvideo

WORKDIR /home/ibladmin/Documents/PYTHON/prefect
ADD ./iblserver_prefect.py /home/ibladmin/Documents/PYTHON/prefect/iblserver_prefect.py
