- name: Make sure docker is already installed
  import_playbook: docker-setup.yaml

- name: Install Nvidia Support for Docker
  hosts: localhost
  become: yes
  tasks:
    - name: Add NVIDIA Container Toolkit GPG key
      apt_key:
        url: https://nvidia.github.io/libnvidia-container/gpgkey
        state: present

    - name: Add NVIDIA Container Toolkit APT repository
      apt_repository:
        repo: deb https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH) /
        state: present
        filename: nvidia-container-toolkit

    - name: Install NVIDIA Container Toolkit
      apt:
        name: nvidia-container-toolkit
        state: present

    - name: Configure NVIDIA Container Toolkit
      command: nvidia-ctk runtime configure --runtime=docker

    - name: Restart Docker service
      systemd:
        name: docker
        state: restarted

    - name: Run Nvidia-smi Inside the GPU Enabled Container
      command: docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi
      register: docker_output
      become: no

    - name: Print Docker Output
      debug:
        var: docker_output.stdout_lines

    - name: Check Docker Nvidia-smi Output
      fail:
        msg: "Docker nvidia-smi failed to run"
      when: "'| NVIDIA-SMI' not in docker_output.stdout"
