"""
Run the behaviour extraction of a session.

The analogue of the photometry container's photometry_sync.py: the tasks are generated by the
respective ibllib function (dynamic_pipeline._get_trials_tasks), registered on alyx as a pipeline
and then run through run_alyx_task.

In contrast to the photometry case this is a task graph and not a single task - one
TrialsRegisterRaw, Trials and (for active protocols) TrainingStatus task per protocol.

Usage: python3 behavior_extraction.py <session_path>
"""

import sys
from pathlib import Path

import ibllib.io.session_params as sess_params
from ibllib.pipes.dynamic_pipeline import _get_trials_tasks
from ibllib.pipes.tasks import Pipeline, run_alyx_task
from one.api import ONE

LOCATION = "server"
DRY = False


def main(session_path: Path) -> None:
    """Create the behaviour tasks of the session on alyx and run them in dependency order."""
    one = ONE(cache_rest=None)
    experiment_description = sess_params.read_params(session_path)

    # the full behaviour task graph, equivalent to the ibllib.pipes.dynamic_pipeline protocol loop
    tasks = _get_trials_tasks(session_path, acquisition_description=experiment_description, one=one)
    pipeline = Pipeline(session_path=session_path, one=one)
    pipeline.tasks = tasks
    task_dicts = pipeline.create_alyx_tasks(rerun__status__in="__all__")

    if DRY:
        return

    # create_alyx_tasks preserves the task order, so parents are complete when their children run
    # (run_alyx_task refetches the job deck and holds a task with unmet dependencies)
    for task_dict in task_dicts:
        run_alyx_task(
            one=one,
            session_path=session_path,
            tdict=task_dict,
            location=LOCATION,
            mode="raise",
        )


if __name__ == "__main__":
    main(Path(sys.argv[1]))
