- name: Make sure docker is already installed
  import_playbook: docker-setup.yaml

- name: Install Nvidia Support for Docker
  hosts: localhost
  become: yes
  tasks:
    - name: Add NVIDIA Container Toolkit GPG key
      apt_key:
        url: https://nvidia.github.io/libnvidia-container/gpgkey
        state: present

    - name: Add NVIDIA Container Toolkit APT repository
      apt_repository:
        repo: deb https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH) /
        state: present
        filename: nvidia-container-toolkit

    - name: Install NVIDIA Container Toolkit
      apt:
        name: nvidia-container-toolkit
        state: present

    - name: Ensure Docker daemon configuration is set
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "default-runtime": "nvidia",
            "runtimes": {
              "nvidia": {
                "path": "nvidia-container-runtime",
                "runtimeArgs": []
              }
            }
          }
 
    - name: Configure NVIDIA Container Toolkit
      command: nvidia-ctk runtime configure --runtime=docker

    - name: Restart Docker service
      systemd:
        name: docker
        state: restarted
