- name: Check Docker Install
  hosts: localhost
  become: no
  tasks:
    - name: Run docker hello-world
      command: docker run hello-world
      register: docker_output

    - name: Print docker output
      debug:
        var: docker_output.stdout_lines

    - name: Check docker hello-world output
      fail:
        msg: "Docker hello-world failed to run"
      when: "'Hello from Docker!' not in docker_output.stdout"
